### PR TITLE
Avoid error on empty country

### LINKED ISSUE #27: Error for this location
https://localhost.api.flow.io/locations?address=Columbia+River,+Washington

returns a server error 

locally:

```
play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[RuntimeException: Could not find country from address [$address]]]
	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:265) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:191) ~[play_2.11-2.4.3.jar:2.4.3]
	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:179) [play_2.11-2.4.3.jar:2.4.3]
	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:212) [play_2.11-2.4.3.jar:2.4.3]
	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:94) [play_2.11-2.4.3.jar:2.4.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [play-netty-server_2.11-2.4.3.jar:2.4.3]
	at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:155) [play-netty-server_2.11-2.4.3.jar:2.4.3]
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36) [scala-library-2.11.8.jar:na]
	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216) [scala-library-2.11.8.jar:na]
	at scala.util.Try$.apply(Try.scala:192) [scala-library-2.11.8.jar:na]
Caused by: java.lang.RuntimeException: Could not find country from address [$address]
	at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.8.jar:na]
	at utils.Google$$anonfun$parseResults$1.apply(Google.scala:92) ~[classes/:na]
	at utils.Google$$anonfun$parseResults$1.apply(Google.scala:82) ~[classes/:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.8.jar:na]
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234) ~[scala-library-2.11.8.jar:na]
	at scala.collection.immutable.List.foreach(List.scala:381) ~[scala-library-2.11.8.jar:na]
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234) ~[scala-library-2.11.8.jar:na]
	at scala.collection.immutable.List.map(List.scala:285) ~[scala-library-2.11.8.jar:na]
	at utils.Google.parseResults(Google.scala:82) ~[classes/:na]
	at utils.Google.getLocationsByAddress(Google.scala:76) ~[classes/:na]
```

### PR DESCRIPTION
**Pull request by mbryzek**
- Fixes #27

### CODE REVIEW

File: api/app/utils/Google.scala [hunk 1]
```diff
@@ -73,12 +74,19 @@ class Google @javax.inject.Inject() (
...
       case results => {
-        Right(parseResults(address, results))
+        Right(sortLocations(parseResults(address, results)))
       }
     }
   }
 
-  private def parseResults(address: String, results: Seq[GeocodingResult]): Seq[Location] = {
+  /**
+    * Ensures locations w/ countries are defined earlier in lost
```
Comment (mikeclimbrock) [inline api/app/utils/Google.scala]: lost=>list

**Comment by mikeclimbrock** [comment]
small typo, lgtm

File: api/app/utils/Google.scala (hunk 1 above)
Comment (mbryzek) [inline api/app/utils/Google.scala]: fixed
